var searchData=
[
  ['addbook',['addBook',['../class_o_o_p_i_i___project___online___book___store_1_1_data_base.html#a9ccf048fd9596c0d412e5ec12f5f812d',1,'OOPII_Project_Online_Book_Store::DataBase']]],
  ['addcustomer',['addCustomer',['../class_o_o_p_i_i___project___online___book___store_1_1_admin_user.html#a7e3d4f01489d6367008e8501e08d01db',1,'OOPII_Project_Online_Book_Store.AdminUser.addCustomer(Customer customer)'],['../class_o_o_p_i_i___project___online___book___store_1_1_admin_user.html#a7e3d4f01489d6367008e8501e08d01db',1,'OOPII_Project_Online_Book_Store.AdminUser.addCustomer(Customer customer)']]],
  ['addmagazine',['addMagazine',['../class_o_o_p_i_i___project___online___book___store_1_1_data_base.html#adafbe3f80e08239e6352c85d9883cc13',1,'OOPII_Project_Online_Book_Store::DataBase']]],
  ['addmusiccd',['addmusicCD',['../class_o_o_p_i_i___project___online___book___store_1_1_data_base.html#a6e1f8cf1e180da5a5397d26c22e7739e',1,'OOPII_Project_Online_Book_Store::DataBase']]],
  ['addnewbook',['addNewBook',['../class_o_o_p_i_i___project___online___book___store_1_1_admin_user.html#af80b593b38779b9c1d8384b1477b63f7',1,'OOPII_Project_Online_Book_Store.AdminUser.addNewBook(String isbn, String author, String publisher, String picture, int page, String name, int id, double price, String issue, BookType type)'],['../class_o_o_p_i_i___project___online___book___store_1_1_admin_user.html#a186688649e2c191aac938fff502ce141',1,'OOPII_Project_Online_Book_Store.AdminUser.addNewBook(String isbn, String author, String publisher, String cover_page_picture, int page, String name, int id, double price)']]],
  ['addnewmagazine',['addNewMagazine',['../class_o_o_p_i_i___project___online___book___store_1_1_admin_user.html#a2c40beac199982ab233d989eb76d8102',1,'OOPII_Project_Online_Book_Store.AdminUser.addNewMagazine(MagazineType type, string issue, String name, int id, double price, String picture)'],['../class_o_o_p_i_i___project___online___book___store_1_1_admin_user.html#aadececdbe47fbfa0bedc169bb6e5e8d2',1,'OOPII_Project_Online_Book_Store.AdminUser.addNewMagazine(MagazineType type, string issue, String name, int id, double price)']]],
  ['addnewmusiccd',['addNewMusicCD',['../class_o_o_p_i_i___project___online___book___store_1_1_admin_user.html#aec889396117e6d550e547731af6ec30c',1,'OOPII_Project_Online_Book_Store.AdminUser.addNewMusicCD(String singer, MusicCDType type, String name, int id, double price, String picture, String issue)'],['../class_o_o_p_i_i___project___online___book___store_1_1_admin_user.html#a67424fdec07f6192af8c74d6b6ed9f65',1,'OOPII_Project_Online_Book_Store.AdminUser.addNewMusicCD(String singer, MusicCDType type, String name, int id, double price)']]],
  ['addorder',['addOrder',['../class_o_o_p_i_i___project___online___book___store_1_1_data_base.html#ae0c67c42c29e9f9da3a3aeddf5a7ea30',1,'OOPII_Project_Online_Book_Store::DataBase']]],
  ['addproduct',['addProduct',['../class_o_o_p_i_i___project___online___book___store_1_1_data_base.html#ab9f16c1e8669862722d13a601f27ccac',1,'OOPII_Project_Online_Book_Store.DataBase.addProduct()'],['../class_o_o_p_i_i___project___online___book___store_1_1_shopping_cart.html#afe57388d8c1c9ce1a098c770f7e2d483',1,'OOPII_Project_Online_Book_Store.ShoppingCart.addProduct(ItemtoPurchase itemtopurchase)'],['../class_o_o_p_i_i___project___online___book___store_1_1_shopping_cart.html#afe57388d8c1c9ce1a098c770f7e2d483',1,'OOPII_Project_Online_Book_Store.ShoppingCart.addProduct(ItemtoPurchase itemtopurchase)']]],
  ['admininterfaceform',['AdminInterfaceForm',['../class_o_o_p_i_i___project___online___book___store_1_1_admin_interface_form.html#aa58b006bd9adebe201e5196193ec2892',1,'OOPII_Project_Online_Book_Store::AdminInterfaceForm']]],
  ['admininterfaceform_5fload',['AdminInterfaceForm_Load',['../class_o_o_p_i_i___project___online___book___store_1_1_admin_interface_form.html#a53d1a5710d69c2646874d53f2d2b1b4e',1,'OOPII_Project_Online_Book_Store::AdminInterfaceForm']]],
  ['adminuser',['AdminUser',['../class_o_o_p_i_i___project___online___book___store_1_1_admin_user.html#ada26223dd6c0369fc3fc426d242d2c3e',1,'OOPII_Project_Online_Book_Store.AdminUser.AdminUser(string name, string adress, string email, string username, string password, int id)'],['../class_o_o_p_i_i___project___online___book___store_1_1_admin_user.html#afa8fb4b2a0f7f41d500f561643d30ca5',1,'OOPII_Project_Online_Book_Store.AdminUser.AdminUser(String name, String adress, String email, String username, String password)']]]
];
